#! /bin/bash

if command -v clang-format-11 > /dev/null; then
    BINARY="clang-format-11"
elif command -v clang-format > /dev/null; then
    BINARY="clang-format"
    VERSION=$(clang-format --version | grep -o '[0-9]\+.[0-9]\+.[0-9]\+' | head -1 | cut -d '.' -f 1)
    if (( $VERSION != 11 )); then
        echo "clang-format version 11 expected, but ${VERSION} found!"
        echo "Please install a suffixed binary (clang-format-11) or install clang-format version 11."
        exit 2
    fi
else
    echo "clang-format not found!"
    echo "Please install clang-format version 11."
    exit 2
fi
echo "Using binary: $BINARY"

$BINARY -style=file -i src/* include/*
